name: Build and Push Docker Image

# Tento workflow se spustí při každém pushi do hlavní větve nebo dle plánovaného cron jobu
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'   # Spustí denní build každý den v 00:00 UTC
  workflow_dispatch:      # Umožní manuální spuštění z GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozitář
      - name: Checkout repository
        uses: actions/checkout@v3

      # Přihlášení do Docker Hubu
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t massimofilippi/php:8.2
      # run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest .

      # Push Docker image do Docker Hubu
      - name: Push Docker image
        run: docker push massimofilippi/php:8.2
      # run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
